
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author michy70
 */
public class priebeh extends javax.swing.JFrame {

    String nazov = "";
    String cesta = "";
    /**
     * Creates new form priebeh
     */
    public priebeh(String nazovp,String cestap) {
        initComponents();
        cesta = cestap;
        nazov = nazovp;
        this.setLocationRelativeTo(null);
        try {
            nacitanie();
        } catch (IOException ex) {
            Logger.getLogger(priebeh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void nacitanie() throws IOException{
        BufferedReader citac = new BufferedReader(new FileReader(nazov));
        String pomoc = "";
        while((pomoc = citac.readLine()) != null){
            if(pomoc.equals("Tabulka Golov")){
                nacitanieGolovAleboTrestov(citac, tabulkaGole);
            } else if(pomoc.equals("Tabulka Trestov")){
                nacitanieGolovAleboTrestov(citac, tabulkaTrestov);
            }
        }
        citac.close();
    }
    
    public void nacitanieGolovAleboTrestov(BufferedReader citac, JTable tabulka) throws IOException{
        int HH = 1;
        for(int i = 0;i<HH;i++){
            String data = citac.readLine();
            if(!data.equals(";")){
                if(i%4 == 0){
                    DefaultTableModel model = (DefaultTableModel) tabulka.getModel();
                    model.addRow(new Object[]{});
                }
                tabulka.getModel().setValueAt(data, i/4, i%4);
                HH++;
            }  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabulkaGole = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabulkaTrestov = new javax.swing.JTable();
        pridatGol = new javax.swing.JButton();
        pridatTrest = new javax.swing.JButton();
        nadpisGole = new javax.swing.JLabel();
        nadpisTresty = new javax.swing.JLabel();
        ulozit = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        tabulkaGole.setBackground(new java.awt.Color(255, 204, 0));
        tabulkaGole.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tabulkaGole.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tabulkaGole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cas", "Gol", "Asistencia 1", "Asistencia 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabulkaGole.setGridColor(new java.awt.Color(0, 0, 204));
        tabulkaGole.setRowHeight(25);
        tabulkaGole.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jScrollPane2.setViewportView(tabulkaGole);

        tabulkaTrestov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cas", "Hrac", "Minuty", "Popis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabulkaTrestov);

        pridatGol.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pridatGol.setText("Pridat gol");
        pridatGol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pridatGolMouseClicked(evt);
            }
        });

        pridatTrest.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        pridatTrest.setText("Pridat trest");
        pridatTrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pridatTrestMouseClicked(evt);
            }
        });

        nadpisGole.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nadpisGole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nadpisGole.setText("Tabulka golov");
        nadpisGole.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        nadpisTresty.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nadpisTresty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nadpisTresty.setText("Tabulka trestov");
        nadpisTresty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        ulozit.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ulozit.setText("Ulozit");
        ulozit.setPreferredSize(new java.awt.Dimension(200, 70));
        ulozit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ulozitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nadpisGole, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pridatGol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pridatTrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(nadpisTresty, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(ulozit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nadpisGole, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(nadpisTresty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pridatTrest)
                    .addComponent(pridatGol))
                .addGap(26, 26, 26)
                .addComponent(ulozit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        zapas zapas1 = new zapas(cesta);
        zapas1.setVisible(true);
        zapas1.pack();
        zapas1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void pridatGolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pridatGolMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabulkaGole.getModel();
        model.addRow(new Object[]{});
    }//GEN-LAST:event_pridatGolMouseClicked

    private void pridatTrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pridatTrestMouseClicked
        DefaultTableModel model = (DefaultTableModel) tabulkaTrestov.getModel();
        model.addRow(new Object[]{});
    }//GEN-LAST:event_pridatTrestMouseClicked

    private void ulozitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ulozitMouseClicked
        try {
            ulozenie();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(priebeh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ulozitMouseClicked

    public void ulozenie() throws FileNotFoundException{
        File subor = new File(nazov);
        PrintWriter zapisovac = new PrintWriter(subor);
        zapisovac.flush();
        zapisovac.println("Tabulka Golov");
        ulozenieGolovAleboTrestov(zapisovac, tabulkaGole);
        zapisovac.println("Tabulka Trestov");
        ulozenieGolovAleboTrestov(zapisovac, tabulkaTrestov);
        zapisovac.close();
    }
    
    public void ulozenieGolovAleboTrestov(PrintWriter zapisovac, JTable tabulka){
        int pocetRiadkov = tabulka.getModel().getRowCount();
        for(int i = 0;i<pocetRiadkov*4;i++){
            if(tabulka.getModel().getValueAt(i / 4, i % 4) != null){
                zapisovac.println(tabulka.getModel().getValueAt(i / 4, i % 4));
            }
        }
        zapisovac.println(";");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(priebeh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(priebeh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(priebeh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(priebeh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new priebeh(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nadpisGole;
    private javax.swing.JLabel nadpisTresty;
    private javax.swing.JButton pridatGol;
    private javax.swing.JButton pridatTrest;
    private javax.swing.JTable tabulkaGole;
    private javax.swing.JTable tabulkaTrestov;
    private javax.swing.JButton ulozit;
    // End of variables declaration//GEN-END:variables
}
