
import javax.swing.JFrame;
import java.io.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author michy70
 */
public class zapas extends javax.swing.JFrame {

    String supiskaA = "supiskaA.txt";
    String supiskaB = "supiskaB.txt";
    String priebeh = "priebeh.txt";
    String nazovOriginalu = "";
    /**
     * Creates new form zapas
     */
    public zapas(String cesta) {
        initComponents();
        //nacitanie nazvu pre vyber textaku
        nazovOriginalu = cesta;
        //nazovOriginalu = "zapas.txt";
        
        this.setLocationRelativeTo(null);
        
        try {
            this.nacitat(nazovOriginalu);
        } catch (IOException ex) {
            Logger.getLogger(zapas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void nacitat(String nazov) throws IOException{
        BufferedReader citac = new BufferedReader(new FileReader(nazov));
        nacitatUdaje(citac);
        citac.close();
    }
    
    public void nacitatUdaje(BufferedReader citac) throws IOException{
        this.jLabelDomaci.setText(citac.readLine());
        this.jLabelHostia.setText(citac.readLine());
        String pomoc = "";
        File subor = new File("pomocka.txt");
        Scanner citac1 = new Scanner(subor);
        if(citac1.hasNext()){
            this.jSpinnerScoreA.setValue(Integer.parseInt(citac1.next()));
            this.jSpinnerScoreB.setValue(Integer.parseInt(citac1.next()));
            this.jLabelTretina.setText(citac1.next());
        } else if((pomoc = citac.readLine()) != null){
            this.jSpinnerScoreA.setValue(Integer.parseInt(pomoc));
            pomoc = citac.readLine();
            this.jSpinnerScoreB.setValue(Integer.parseInt(pomoc));
            pomoc = citac.readLine();
            this.jLabelTretina.setText(pomoc);
            if((pomoc = citac.readLine()) != null){
                nacitatSupiskyPriebeh(citac);  
            }
        }
        citac1.close();
    }
    
    public void nacitatSupiskyPriebeh(BufferedReader citac) throws FileNotFoundException, IOException{
        String pomoc = "";
        
        File subor = new File(supiskaA);
        PrintWriter zapisovac = new PrintWriter(subor);
        while(!(pomoc = citac.readLine()).equals("Hostia")){
            zapisovac.println(pomoc);
        }
        zapisovac.close();
        
        subor = new File(supiskaB);
        zapisovac = new PrintWriter(subor);
        while(!(pomoc = citac.readLine()).equals("Priebeh")){
            zapisovac.println(pomoc);
        }
        zapisovac.close();
        
        subor = new File(priebeh);
        zapisovac = new PrintWriter(subor);
        while((pomoc = citac.readLine()) != null){
            zapisovac.println(pomoc);
        }
        zapisovac.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPozadie = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelMini = new javax.swing.JLabel();
        jPanelUloz = new javax.swing.JPanel();
        jLabelUloz = new javax.swing.JLabel();
        jPanelScoreA = new javax.swing.JPanel();
        jSpinnerScoreA = new javax.swing.JSpinner();
        jPanelScoreB = new javax.swing.JPanel();
        jSpinnerScoreB = new javax.swing.JSpinner();
        jPanelNazovB = new javax.swing.JPanel();
        jLabelHostia = new javax.swing.JLabel();
        jPanelTretina = new javax.swing.JPanel();
        jLabelTretina = new javax.swing.JLabel();
        jButtonMinus = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jPanelPriebeh = new javax.swing.JPanel();
        jLabelPriebeh = new javax.swing.JLabel();
        jPanelSupiskaHostia = new javax.swing.JPanel();
        jLabelSupiskaHostia = new javax.swing.JLabel();
        jPanelSupiskaDomaci = new javax.swing.JPanel();
        jLabelSupiskaDomaci = new javax.swing.JLabel();
        jPanelNazovA = new javax.swing.JPanel();
        jLabelDomaci = new javax.swing.JLabel();
        domaci = new javax.swing.JLabel();
        hostia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelPozadie.setBackground(new java.awt.Color(102, 102, 255));
        jPanelPozadie.setPreferredSize(new java.awt.Dimension(1500, 800));

        jPanelMenu.setBackground(new java.awt.Color(255, 51, 102));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(1500, 50));
        jPanelMenu.setLayout(null);

        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setPreferredSize(new java.awt.Dimension(50, 50));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        jPanelMenu.add(jLabelExit);
        jLabelExit.setBounds(1450, 0, 50, 50);

        jLabelMini.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMini.setText("—");
        jLabelMini.setPreferredSize(new java.awt.Dimension(50, 50));
        jLabelMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMiniMouseClicked(evt);
            }
        });
        jPanelMenu.add(jLabelMini);
        jLabelMini.setBounds(1400, 0, 50, 50);

        jPanelUloz.setBackground(new java.awt.Color(255, 255, 0));
        jPanelUloz.setMinimumSize(new java.awt.Dimension(136, 46));
        jPanelUloz.setPreferredSize(new java.awt.Dimension(140, 50));

        jLabelUloz.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUloz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUloz.setText("Ulozit");
        jLabelUloz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 6, true));
        jLabelUloz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUlozMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelUlozLayout = new javax.swing.GroupLayout(jPanelUloz);
        jPanelUloz.setLayout(jPanelUlozLayout);
        jPanelUlozLayout.setHorizontalGroup(
            jPanelUlozLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUlozLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelUloz, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelUlozLayout.setVerticalGroup(
            jPanelUlozLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUlozLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelUloz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMenu.add(jPanelUloz);
        jPanelUloz.setBounds(100, 0, 140, 50);

        jPanelScoreA.setPreferredSize(new java.awt.Dimension(200, 200));

        jSpinnerScoreA.setFont(new java.awt.Font("Tahoma", 1, 125)); // NOI18N

        javax.swing.GroupLayout jPanelScoreALayout = new javax.swing.GroupLayout(jPanelScoreA);
        jPanelScoreA.setLayout(jPanelScoreALayout);
        jPanelScoreALayout.setHorizontalGroup(
            jPanelScoreALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScoreALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSpinnerScoreA, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelScoreALayout.setVerticalGroup(
            jPanelScoreALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScoreALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSpinnerScoreA, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelScoreB.setPreferredSize(new java.awt.Dimension(200, 200));

        jSpinnerScoreB.setFont(new java.awt.Font("Tahoma", 1, 125)); // NOI18N

        javax.swing.GroupLayout jPanelScoreBLayout = new javax.swing.GroupLayout(jPanelScoreB);
        jPanelScoreB.setLayout(jPanelScoreBLayout);
        jPanelScoreBLayout.setHorizontalGroup(
            jPanelScoreBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScoreBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSpinnerScoreB, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelScoreBLayout.setVerticalGroup(
            jPanelScoreBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScoreBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSpinnerScoreB, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelNazovB.setPreferredSize(new java.awt.Dimension(600, 100));

        jLabelHostia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelHostia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHostia.setText("tym B");

        javax.swing.GroupLayout jPanelNazovBLayout = new javax.swing.GroupLayout(jPanelNazovB);
        jPanelNazovB.setLayout(jPanelNazovBLayout);
        jPanelNazovBLayout.setHorizontalGroup(
            jPanelNazovBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNazovBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHostia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNazovBLayout.setVerticalGroup(
            jPanelNazovBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNazovBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHostia, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTretina.setBackground(new java.awt.Color(102, 102, 255));
        jPanelTretina.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanelTretina.setLayout(null);

        jLabelTretina.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabelTretina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTretina.setText("0");
        jLabelTretina.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanelTretina.add(jLabelTretina);
        jLabelTretina.setBounds(0, 0, 140, 100);

        jButtonMinus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.setPreferredSize(new java.awt.Dimension(50, 46));
        jButtonMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMinusMouseClicked(evt);
            }
        });
        jPanelTretina.add(jButtonMinus);
        jButtonMinus.setBounds(140, 50, 52, 46);

        jButtonPlus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.setPreferredSize(new java.awt.Dimension(50, 46));
        jButtonPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPlusMouseClicked(evt);
            }
        });
        jPanelTretina.add(jButtonPlus);
        jButtonPlus.setBounds(140, 0, 52, 46);

        jLabelPriebeh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPriebeh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPriebeh.setText("Priebeh zapasu");
        jLabelPriebeh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPriebehMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelPriebehLayout = new javax.swing.GroupLayout(jPanelPriebeh);
        jPanelPriebeh.setLayout(jPanelPriebehLayout);
        jPanelPriebehLayout.setHorizontalGroup(
            jPanelPriebehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPriebehLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPriebeh, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPriebehLayout.setVerticalGroup(
            jPanelPriebehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPriebehLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPriebeh, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelSupiskaHostia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSupiskaHostia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSupiskaHostia.setText("Supiska / Zostava (hostia)");
        jLabelSupiskaHostia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSupiskaHostiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSupiskaHostiaLayout = new javax.swing.GroupLayout(jPanelSupiskaHostia);
        jPanelSupiskaHostia.setLayout(jPanelSupiskaHostiaLayout);
        jPanelSupiskaHostiaLayout.setHorizontalGroup(
            jPanelSupiskaHostiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupiskaHostiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSupiskaHostia, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSupiskaHostiaLayout.setVerticalGroup(
            jPanelSupiskaHostiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupiskaHostiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSupiskaHostia, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelSupiskaDomaci.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelSupiskaDomaci.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSupiskaDomaci.setText("Supiska / Zostava (domaci)");
        jLabelSupiskaDomaci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSupiskaDomaciMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSupiskaDomaciLayout = new javax.swing.GroupLayout(jPanelSupiskaDomaci);
        jPanelSupiskaDomaci.setLayout(jPanelSupiskaDomaciLayout);
        jPanelSupiskaDomaciLayout.setHorizontalGroup(
            jPanelSupiskaDomaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupiskaDomaciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSupiskaDomaci, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSupiskaDomaciLayout.setVerticalGroup(
            jPanelSupiskaDomaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupiskaDomaciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSupiskaDomaci, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelNazovA.setPreferredSize(new java.awt.Dimension(600, 100));

        jLabelDomaci.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDomaci.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDomaci.setText("tym A");

        javax.swing.GroupLayout jPanelNazovALayout = new javax.swing.GroupLayout(jPanelNazovA);
        jPanelNazovA.setLayout(jPanelNazovALayout);
        jPanelNazovALayout.setHorizontalGroup(
            jPanelNazovALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNazovALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDomaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNazovALayout.setVerticalGroup(
            jPanelNazovALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNazovALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDomaci, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        domaci.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        domaci.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        domaci.setText("DOMACI");

        hostia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hostia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hostia.setText("HOSTIA");

        javax.swing.GroupLayout jPanelPozadieLayout = new javax.swing.GroupLayout(jPanelPozadie);
        jPanelPozadie.setLayout(jPanelPozadieLayout);
        jPanelPozadieLayout.setHorizontalGroup(
            jPanelPozadieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPozadieLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jPanelScoreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTretina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225)
                .addComponent(jPanelScoreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
            .addGroup(jPanelPozadieLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelPozadieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPozadieLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelSupiskaDomaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jPanelPriebeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jPanelSupiskaHostia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPozadieLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanelPozadieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(domaci, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(jPanelNazovA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPozadieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelNazovB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hostia, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                        .addGap(124, 124, 124))))
        );
        jPanelPozadieLayout.setVerticalGroup(
            jPanelPozadieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPozadieLayout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanelPozadieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domaci, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPozadieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelNazovB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelNazovA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanelPozadieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelScoreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelScoreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTretina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanelPozadieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPriebeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSupiskaDomaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSupiskaHostia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPozadie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPozadie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlusMouseClicked
        if(jLabelTretina.getText().equals("0")){
            jLabelTretina.setText("1");
        } else if(jLabelTretina.getText().equals("1")){
            jLabelTretina.setText("2");
        } else {
            jLabelTretina.setText("3");
        }
    }//GEN-LAST:event_jButtonPlusMouseClicked

    private void jButtonMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinusMouseClicked
        String nic = jLabelTretina.getText();
        if(jLabelTretina.getText().equals("3")){
            jLabelTretina.setText("2");
        } else if(jLabelTretina.getText().equals("2")){
            jLabelTretina.setText("1");
        } else {
            jLabelTretina.setText("0");
        }
    }//GEN-LAST:event_jButtonMinusMouseClicked

    private void jLabelUlozMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUlozMouseClicked
        String nazov = this.jLabelDomaci.getText() + "--vs--" + this.jLabelHostia.getText() + ".txt";

        try {
            this.zapis(nazovOriginalu);
        } catch (IOException ex) {
            Logger.getLogger(zapas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelUlozMouseClicked

    private void jLabelMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMiniMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMiniMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        try {
            exit();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(zapas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(zapas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            turnaj turnaj1 = new turnaj(false);
            turnaj1.setVisible(true);
            turnaj1.pack();
            turnaj1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(zapas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelExitMouseClicked

    public void exit() throws FileNotFoundException, IOException{        
        File subor = new File(supiskaA);
        PrintWriter zapisovac = new PrintWriter(subor);
        zapisovac.flush();
        zapisovac.close();
        
        subor = new File(supiskaB);
        zapisovac = new PrintWriter(subor);
        zapisovac.flush();
        zapisovac.close();
        
        subor = new File(priebeh);
        zapisovac = new PrintWriter(subor);
        zapisovac.flush();
        zapisovac.close();
        
        subor = new File("pomocka.txt");
        zapisovac = new PrintWriter(subor);
        zapisovac.flush();
        zapisovac.close();
    }
    
    private void jLabelPriebehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPriebehMouseClicked
        try {
            zapisanieSkore();
        } catch (IOException ex) {
            Logger.getLogger(zapas.class.getName()).log(Level.SEVERE, null, ex);
        }
        priebeh priebeh1 = new priebeh(priebeh,nazovOriginalu);
        priebeh1.setVisible(true);
        priebeh1.pack();
        priebeh1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelPriebehMouseClicked

    private void jLabelSupiskaDomaciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSupiskaDomaciMouseClicked
        try {
            zapisanieSkore();
        } catch (IOException ex) {
            Logger.getLogger(zapas.class.getName()).log(Level.SEVERE, null, ex);
        }
        supiskaZostava domaci = new supiskaZostava(supiskaA,nazovOriginalu);
        domaci.setVisible(true);
        domaci.pack();
        domaci.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSupiskaDomaciMouseClicked

    private void jLabelSupiskaHostiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSupiskaHostiaMouseClicked
        try {
            zapisanieSkore();
        } catch (IOException ex) {
            Logger.getLogger(zapas.class.getName()).log(Level.SEVERE, null, ex);
        }
        supiskaZostava hostia = new supiskaZostava(supiskaB,nazovOriginalu);
        hostia.setVisible(true);
        hostia.pack();
        hostia.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelSupiskaHostiaMouseClicked

    public void zapisanieSkore() throws IOException{
        File subor = new File("pomocka.txt");
        PrintWriter zapisovac = new PrintWriter(subor);
        zapisovac.flush();
        zapisovac.println(this.jSpinnerScoreA.getValue());
        zapisovac.println(this.jSpinnerScoreB.getValue());
        zapisovac.println(this.jLabelTretina.getText());
        zapisovac.close();
    }
    
    public void zapis(String nazov) throws IOException{
        File subor = new File(nazov);
        PrintWriter zapisovac = new PrintWriter(subor);
        zapisovac.println(this.jLabelDomaci.getText());
        zapisovac.println(this.jLabelHostia.getText());
        zapisovac.println(this.jSpinnerScoreA.getValue());
        zapisovac.println(this.jSpinnerScoreB.getValue());
        zapisovac.println(this.jLabelTretina.getText());

        
        zapisUdajov(zapisovac);

        zapisovac.close();
    }
    
    public void zapisUdajov(PrintWriter zapisovac) throws IOException{
        BufferedReader citacA = new BufferedReader(new FileReader(supiskaA));
        String pomoc = "";
        
        zapisovac.println("Domaci");
        while((pomoc = citacA.readLine()) != null){
            zapisovac.println(pomoc);
        }
        citacA.close();
        
        citacA = new BufferedReader(new FileReader(supiskaB));
        zapisovac.println("Hostia");
        while((pomoc = citacA.readLine()) != null){
            zapisovac.println(pomoc);
        }
        citacA.close();

        citacA = new BufferedReader(new FileReader(priebeh));
        zapisovac.println("Priebeh");
        while((pomoc = citacA.readLine()) != null){
            zapisovac.println(pomoc);
        }
        citacA.close();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(zapas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(zapas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(zapas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(zapas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new zapas(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel domaci;
    private javax.swing.JLabel hostia;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JLabel jLabelDomaci;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelHostia;
    private javax.swing.JLabel jLabelMini;
    private javax.swing.JLabel jLabelPriebeh;
    private javax.swing.JLabel jLabelSupiskaDomaci;
    private javax.swing.JLabel jLabelSupiskaHostia;
    private javax.swing.JLabel jLabelTretina;
    private javax.swing.JLabel jLabelUloz;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNazovA;
    private javax.swing.JPanel jPanelNazovB;
    private javax.swing.JPanel jPanelPozadie;
    private javax.swing.JPanel jPanelPriebeh;
    private javax.swing.JPanel jPanelScoreA;
    private javax.swing.JPanel jPanelScoreB;
    private javax.swing.JPanel jPanelSupiskaDomaci;
    private javax.swing.JPanel jPanelSupiskaHostia;
    private javax.swing.JPanel jPanelTretina;
    private javax.swing.JPanel jPanelUloz;
    private javax.swing.JSpinner jSpinnerScoreA;
    private javax.swing.JSpinner jSpinnerScoreB;
    // End of variables declaration//GEN-END:variables
}
